### ISSUE TITLE
Unable to correctly parse Windows gradle files

### ISSUE THREAD

**Issue by mbwhite** [ninetwozero/gradle-to-js#25]
If the build.gradle file has comes from Windows with \r\n line terminators, the parsing doesn't quite get it right.

I was ready from a file directly, but worked around it by reading the file myself, and applying

`g2js.parseText(str.replace(/\r\n/g,'\n'))`

Could raise a PR but not sure within the parse how you'd prefer this to be handled.

**Comment by karllindmark** [comment]
Hi @mbwhite, thanks for the report!

Would you mind providing me with a small sample so that I can see where the expected behavior doesn't match the current implementation? 

I'm thinking one would have to make the CHAR_NEWLINE detection all over the place consist of checking for charCode==13 as well, which is Carriage Return. I have a fix ready locally, but I'd love to run it towards your test data to verify that we're fixing it.

Thanks!

**Comment by mbwhite** [comment]
The key part of the build.gradle is 

```
plugins {
    id 'com.github.johnrengelman.shadow' version '2.0.3'
    id 'java'
}
version '0.0.1'
sourceCompatibility = 1.8
```

To reproduce in VSCode I created a new file - but ensured that I save it with the CRLF format.

Running this JavaScript..
```
var g2js = require('gradle-to-js/lib/parser');

g2js.parseFile('./build.gradle.win').then(function(representation) {
  console.log(representation);
});
```

Gives this output

```
{ plugins:
   { id:
      [ '\'com.github.johnrengelman.shadow\' version \'2.0.3\'\r',
        '\'java\'\r' ] },
  version: '\'0.0.1\'\r',
  sourceCompatibility: '1.8\r' }
```

When it should be...

```
{ plugins:
   { id:
      [ '\'com.github.johnrengelman.shadow\' version \'2.0.3\'',
        'java' ] },
  version: '0.0.1',
  sourceCompatibility: '1.8' }
```

**Comment by karllindmark** [comment]
Hi @mbwhite, the next release will include the fix for this, but also a better format for the plugins closure:

Something like:


```
plugins: [
    {
        id: 'com.github.johnrengelman.shadow',
        version: '2.0.3'
    },
    {
        'id': 'java'
    }
]
```

Hope it helps!
