### ISSUE TITLE
parsing issue occurs in case build.gradle file contains several 'android' closures

### ISSUE THREAD

**Issue by sergey-akhalkov** [ninetwozero/gradle-to-js#4]
Hello! The issue occurs when I've tried to execute `parseFile` method on [this build.gradle file](https://gist.github.com/mateusreis/15c0370766536634ac34003eafb80bef)
Parsing result represents `android` prop as array instead of object.

**Comment by karllindmark** [comment]
Good morning Sergey, and thanks for reporting this issue!

I'll have to give it a run through later when I'm by my computer, but my
spontaneous thought is that the two Android closures are being grouped into
the array due to the multiple occurrences of the key. They probably don't
need that behavior and can just be merged together into an object. Maybe. 🤔

I'll get back to you!

Best regards,
Karl

**Comment by sergey-akhalkov** [comment]
@karllindmark, it seems to be good solution to merge closures together and receive an common object after parsing. Thank you!

**Comment by karllindmark** [comment]
Hi @sergey-akhalkov!

Do you have a minute to try out #5 and see if it works as you expect it to?

**Comment by sergey-akhalkov** [comment]
Hi @karllindmark, yeah, works fine! Thanks!

**Comment by karllindmark** [comment]
This functionality is now present in `gradle-to-js@0.2.5`. 💪

**Comment by sergey-akhalkov** [comment]
@karllindmark, great! I will update the package version.
